name: Greetings

on: [pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Hello and thank you for your contribution. Please allow up to 48 hours to get a review on your pull request. Meanwhile, make sure to read our [code of conduct](https://github.com/J-Human/J-Human/blob/main/.github/CODE_OF_CONDUCT.md) and check out our [discussions](https://github.com/J-Human/J-Human/discussions) tab.'
